### ISSUE TITLE
How to enable debug

### ISSUE THREAD

**Issue by jseiser** [apptality/aws-ecs-cloudmap-prometheus-sd#2]
We are wanting to use this software to extend our monitoring to our ECS services, but havent been able to get it to work.  We would love a way to enable the debug logging, so we can try to see whats going on.

A few notes, Im running it locally, so it does not have any network access to these actual services, I assume thats fine.  We do use govcloud, which maybe is an issue?

```
services:
  ecs:
    image: apptality/aws-ecs-cloudmap-prometheus-discovery:latest 
    ports:
      - "9001:9001"
    environment:
      DiscoveryOptions__EcsClusters: "ecs-dev;"
      AWS_REGION: "us-gov-west-1"
      AWS_ACCESS_KEY_ID: "xxxxxx"
      AWS_SECRET_ACCESS_KEY: "xxxxxx"
      DiscoveryOptions__EcsTaskTags: "*"
      DiscoveryOptions__EcsServiceTags: "*"
      ASPNETCORE_URLS: "http://*:9001"
    healthcheck:
      test: curl --fail http://localhost:9001/health || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - ecs
networks:
  ecs:
    name: ecs
```

```
❯ docker compose up                                                                                                    │
[+] Running 1/1                                                                                                        │~ [🐳 desktop-linux]took 3s 
 ✔ Container justin-ecs-1  Recreated                                                                              0.2s │❯ curl http://localhost:9001/prometheus-targets
Attaching to ecs-1                                                                                                     │[]%                                                                                                                   
ecs-1  | 2024-10-17 19:06:35.400 +00:00 [INF] Started 'ECS Prometheus Discovery' application                           │
ecs-1  | 2024-10-17 19:06:41.375 +00:00 [INF] Found credentials using the AWS SDK's default credential search          │~ [🐳 desktop-linux]took 2s 
ecs-1  | 2024-10-17 19:06:41.386 +00:00 [INF] Found credentials using the AWS SDK's default credential search          │❯ curl http://localhost:9001/prometheus-targets
ecs-1  | 2024-10-17 19:06:44.604 +00:00 [INF] HTTP GET /prometheus-targets responded 200 in 3238.5394 ms    
```

```
curl http://localhost:9001/prometheus-targets
[]%  
```

So its def. doing something, but the cluster listed has like 20+ services in it, so I would hope to see something.

Thanks.
